### ISSUE TITLE
NullPointerException with scheduler.driver set

### ISSUE THREAD

**Issue by x7airworker** [JavaWebStack/web-framework#6]
**Describe the Bug**
set `SCHEDULER_DRIVER` to `DATABASE` in your .env file.

**Expected behavior**
No exception

**Screenshots / Logs**
Exception in thread "main" java.lang.NullPointerException
	at org.javawebstack.framework.WebApplication.<init>(WebApplication.java:120)
	at de.aurum.bot.AurumBot.<init>(AurumBot.java:28)
	at de.aurum.bot.AurumBot.main(AurumBot.java:30)

**Environment Information:**
 - Java version: adopt-openjdk-1.8.0_252
 - Version 1.0

**Comment by JulianFun123** [comment]
The Models were not registered. Done

**Comment by x7airworker** [comment]
Thanks for the fix, but now I get an ORMQueryException
```
Exception in thread "main" org.javawebstack.orm.exception.ORMQueryException: BLOB/TEXT column 'name' used in key specification without a key length
	at org.javawebstack.orm.migration.AutoMigrator.migrateTable(AutoMigrator.java:97)
	at org.javawebstack.orm.migration.AutoMigrator.migrate(AutoMigrator.java:30)
	at org.javawebstack.orm.migration.AutoMigrator.migrate(AutoMigrator.java:19)
	at org.javawebstack.orm.Repo.autoMigrate(Repo.java:247)
	at org.javawebstack.framework.WebApplication.<init>(WebApplication.java:124)
	at de.aurum.bot.AurumBot.<init>(AurumBot.java:28)
	at de.aurum.bot.AurumBot.main(AurumBot.java:30)
```

**Comment by JulianFun123** [comment]
Should be now fixed. I added a size of 255 for the field `name`
